name: NoBasis-validator

on:
   workflow_dispatch:

env:
  IG: no-basis

# The following jobs are equal for all IGs and can be moved to a common composite-action if 'uses'-support is added, see:
# https://github.com/actions/runner/blob/main/docs/adrs/1144-composite-actions.md
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Persist the FHIR Package Cache between runners.
      # Doc: https://confluence.hl7.org/display/FHIR/FHIR+Package+Cache
      - name: 🗂️ Cache FHIR Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.fhir/packages
          key: fhir-packages

      # Persist the IG Publisher input-cache between runners.
      # Doc: https://build.fhir.org/ig/FHIR/ig-guidance/using-templates.html#igroot-input-cache
      - name: 🗂️ Cache IG Publisher input-cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.IG }}/input-cache
          key: ig-publisher-input-cache           

      # Downloads the newest version of the IG Publisher, this could probable be cached.
      - name: 📥 Download IG Publisher
        run: wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar

      # Validate the IG
      - name: 🏃‍♂️ Run IG Publisher validate mode
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -jar validator_cli.jar 
